### ISSUE TITLE
apparmor blocks passt running

### ISSUE THREAD

**Issue by hmoffatt** [alvistack/passt-top-passt#1]
When I try to run podman with a pasta network on Debian 12, apparmor blocks passt from working:

```
$ podman run -it --rm --network=pasta debian
Error: pasta failed with exit code 1:
Couldn't open network namespace /run/user/1000/netns/netns-5885e942-e72b-c128-3718-49761d88b72d: Permission denied
```

Kernel log shows

```
[  101.894352] audit: type=1400 audit(1717554896.337:16): apparmor="DENIED" operation="open" profile="passt" name="/run/user/1000/netns/netns-5885e942-e72b-c128-3718-49761d88b72d" pid=561 comm="passt.avx2" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

**Comment by hswong3i** [comment]
Good catch, shall we first report to https://passt.top/passt, so if patch/fix/PR could provided, I will quick apply to this fork and DEB/RPM at https://build.opensuse.org/project/show/home:alvistack?

**Comment by hmoffatt** [comment]
I looked through the bug tracker and git there and I don't see anything relevant, so I assume it works for them and there's something different in our environment.  But I agree it needs to go upstream for help.

Would you like me to open a bug there or will you? Thanks.

**Comment by Luap99** [comment]
You need to create hard links for pasta and passt, with a symlink it will use the wrong profile, see https://github.com/containers/buildah/issues/5440#issuecomment-2028911573

**Comment by hmoffatt** [comment]
> You need to create hard links for pasta and passt, with a symlink it will use the wrong profile, see [containers/buildah#5440 (comment)](https://github.com/containers/buildah/issues/5440#issuecomment-2028911573)

Indeed, that fixes it. Thanks.

**Comment by sbrivio-rh** [comment]
See also: https://archives.passt.top/passt-user/20240607201617.757cdd1b@elisabeth/: this is already fixed in official packages for Debian, openSUSE, Ubuntu.

Note that if you're using SELinux instead, you need *copies*, hard links won't be enough (see how the official Fedora package deals with it).

**Comment by hswong3i** [comment]
@sbrivio-rh I just simply patch the Makefile from `ln` to `cp`, so both my DEB/RPM could get fixed in sync, see https://github.com/alvistack/passt-top-passt/commit/74040e0e7e2fb158b4f25e95786ee2d28540c2e7#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R124:
```
diff --git a/Makefile b/Makefile
index c1e1f06..414c915 100644
--- a/Makefile
+++ b/Makefile
@@ -121,7 +121,7 @@ passt.avx2: $(PASST_SRCS) $(HEADERS)
 passt.avx2: passt
 
 pasta.avx2 pasta.1 pasta: pasta%: passt%
-       ln -sf $< $@
+       cp -rfp $< $@
 
 qrap: $(QRAP_SRCS) passt.h
        $(CC) $(FLAGS) $(CFLAGS) $(CPPFLAGS) $(QRAP_SRCS) -o qrap $(LDFLAGS)
```

**Comment by hmoffatt** [comment]
This is working in 100:0.0+20240607.8a83b530-1, thanks @hswong3i and @sbrivio-rh .
